# Generated by Django 4.2.1 on 2023-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_exerciselist_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workouts',
        ),
        migrations.AddField(
            model_name='profile',
            name='workouts',
            field=models.ManyToManyField(to='workouts.workout'),
        ),
    ]
