# Generated by Django 4.2.1 on 2023-06-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_profile_workouts_profile_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workouts',
        ),
    ]
