# Generated by Django 4.2.1 on 2023-06-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_profile_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workout'),
        ),
    ]
