# Generated by Django 4.2.1 on 2023-06-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_profile_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workout',
        ),
    ]
