# Generated by Django 4.2.1 on 2023-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_profile_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='muscle_groups',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='type',
            field=models.CharField(choices=[('bw', 'Bodyweight'), ('weighted', 'weighted')], default='bw', max_length=50),
        ),
    ]
