# Generated by Django 4.2.1 on 2023-06-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_exercises_muscle_groups_alter_exercises_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='intensity',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=2),
        ),
    ]
