# Generated by Django 4.2.1 on 2023-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_exercises_intensity_alter_exercises_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='intensity',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=1, null=True),
        ),
    ]
